[package]
name = "bathy-scope"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bathy-types = { path = "../bathy-types" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
ipnet = { workspace = true }
time = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
